// <auto-generated />
using System;
using System.Net;
using Inventario.Data.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Inventario.Data.Migrations
{
    [DbContext(typeof(InventarioContext))]
    [Migration("20260717170332_CrearTablaHistorialLogs")]
    partial class CrearTablaHistorialLogs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Inventario.Data.Models.CatalogoArchivo", b =>
                {
                    b.Property<int>("IdArchivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_archivo");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("IdArchivo"));

                    b.Property<string>("Archivo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("archivo");

                    b.Property<DateTime?>("FechaSubida")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_subida");

                    b.Property<string>("NombreArchivo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombre_archivo");

                    b.HasKey("IdArchivo")
                        .HasName("catalogo_archivos_pkey");

                    b.ToTable("catalogo_archivos", (string)null);
                });

            modelBuilder.Entity("Inventario.Data.Models.CatalogoBroker", b =>
                {
                    b.Property<int>("IdBroker")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_broker");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("IdBroker"));

                    b.Property<string>("NombreBroker")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre_broker");

                    b.HasKey("IdBroker")
                        .HasName("catalogo_brokers_pkey");

                    b.ToTable("catalogo_brokers", (string)null);
                });

            modelBuilder.Entity("Inventario.Data.Models.CatalogoEconomico", b =>
                {
                    b.Property<string>("IdEconomico")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("id_economico");

                    b.Property<int?>("Consecutivo")
                        .HasColumnType("integer")
                        .HasColumnName("consecutivo");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<string>("Dimensiones")
                        .HasColumnType("text");

                    b.Property<bool>("EstatusSeguro")
                        .HasColumnType("boolean")
                        .HasColumnName("estatus_seguro");

                    b.Property<string>("FamiliaMotor")
                        .HasColumnType("text")
                        .HasColumnName("familia_motor");

                    b.Property<string>("GradoPropiedad")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("grado_propiedad");

                    b.Property<decimal?>("Horometro")
                        .HasColumnType("numeric")
                        .HasColumnName("horometro");

                    b.Property<int>("IdAdministrador")
                        .HasColumnType("integer")
                        .HasColumnName("id_administrador");

                    b.Property<int>("IdCombustible")
                        .HasColumnType("integer")
                        .HasColumnName("id_combustible");

                    b.Property<int?>("IdEstatus")
                        .HasColumnType("integer")
                        .HasColumnName("id_estatus");

                    b.Property<string>("IdGrupo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("id_grupo");

                    b.Property<int>("IdMarca")
                        .HasColumnType("integer")
                        .HasColumnName("id_marca");

                    b.Property<int>("IdOperador")
                        .HasColumnType("integer")
                        .HasColumnName("id_operador");

                    b.Property<int>("IdPropietario")
                        .HasColumnType("integer")
                        .HasColumnName("id_propietario");

                    b.Property<int>("IdResponsable")
                        .HasColumnType("integer")
                        .HasColumnName("id_responsable");

                    b.Property<string>("IdTipoEquipo")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("id_tipo_equipo");

                    b.Property<int>("IdUbicacion")
                        .HasColumnType("integer")
                        .HasColumnName("id_ubicacion");

                    b.Property<int>("MarcaMotor")
                        .HasColumnType("integer")
                        .HasColumnName("marca_motor");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("modelo");

                    b.Property<string>("ModeloMotor")
                        .HasColumnType("text")
                        .HasColumnName("modelo_motor");

                    b.Property<string>("Motor")
                        .HasColumnType("text")
                        .HasColumnName("motor");

                    b.Property<string>("ObservacionesAsignaciones")
                        .HasColumnType("text")
                        .HasColumnName("observaciones_asignaciones");

                    b.Property<int?>("PeriodoFabricacion")
                        .HasColumnType("integer")
                        .HasColumnName("periodo_fabricacion");

                    b.Property<string>("Placas")
                        .HasColumnType("text")
                        .HasColumnName("placas");

                    b.Property<string>("PolizaAdjunta")
                        .HasColumnType("text")
                        .HasColumnName("poliza_adjunta");

                    b.Property<string>("Serie")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("serie");

                    b.Property<string>("SerieMotor")
                        .HasColumnType("text")
                        .HasColumnName("serie_motor");

                    b.Property<string>("THK")
                        .HasColumnType("text")
                        .HasColumnName("THK");

                    b.HasKey("IdEconomico")
                        .HasName("catalogo_economicos_pkey");

                    b.HasIndex("IdMarca");

                    b.HasIndex("MarcaMotor");

                    b.HasIndex(new[] { "IdAdministrador" }, "IX_catalogo_economicos_id_administrador");

                    b.HasIndex(new[] { "IdCombustible" }, "IX_catalogo_economicos_id_combustible");

                    b.HasIndex(new[] { "IdEstatus" }, "IX_catalogo_economicos_id_estatus");

                    b.HasIndex(new[] { "IdGrupo" }, "IX_catalogo_economicos_id_grupo");

                    b.HasIndex(new[] { "IdOperador" }, "IX_catalogo_economicos_id_operador");

                    b.HasIndex(new[] { "IdPropietario" }, "IX_catalogo_economicos_id_propietario");

                    b.HasIndex(new[] { "IdResponsable" }, "IX_catalogo_economicos_id_responsable");

                    b.HasIndex(new[] { "IdTipoEquipo" }, "IX_catalogo_economicos_id_tipo_equipo");

                    b.HasIndex(new[] { "IdUbicacion" }, "IX_catalogo_economicos_id_ubicacion");

                    b.ToTable("catalogo_economicos", (string)null);
                });

            modelBuilder.Entity("Inventario.Data.Models.CatalogoEstatus", b =>
                {
                    b.Property<int>("IdEstatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_estatus");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("IdEstatus"));

                    b.Property<string>("DescripcionEstatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descripcion_estatus");

                    b.HasKey("IdEstatus")
                        .HasName("catalogo_estatus_pkey");

                    b.ToTable("catalogo_estatus", (string)null);
                });

            modelBuilder.Entity("Inventario.Data.Models.CatalogoFrente", b =>
                {
                    b.Property<int>("IdFrente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_frente");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("IdFrente"));

                    b.Property<int>("IdTramo")
                        .HasColumnType("integer")
                        .HasColumnName("id_tramo");

                    b.Property<string>("NombreFrente")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre_frente");

                    b.HasKey("IdFrente")
                        .HasName("catalogo_frentes_pkey");

                    b.HasIndex(new[] { "IdTramo" }, "IX_catalogo_frentes_id_tramo");

                    b.ToTable("catalogo_frentes", (string)null);
                });

            modelBuilder.Entity("Inventario.Data.Models.CatalogoGrupo", b =>
                {
                    b.Property<string>("IdGrupo")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("id_grupo");

                    b.Property<string>("DescripcionGrupo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descripcion_grupo");

                    b.HasKey("IdGrupo")
                        .HasName("catalogo_grupos_pkey");

                    b.ToTable("catalogo_grupos", (string)null);
                });

            modelBuilder.Entity("Inventario.Data.Models.CatalogoMarca", b =>
                {
                    b.Property<int>("IdMarca")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_marca");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("IdMarca"));

                    b.Property<string>("NombreMarca")
                        .HasColumnType("text")
                        .HasColumnName("nombre_marca");

                    b.HasKey("IdMarca")
                        .HasName("catalogo_marcas_pkey");

                    b.ToTable("catalogo_marcas", (string)null);
                });

            modelBuilder.Entity("Inventario.Data.Models.CatalogoMovimientosEconomico", b =>
                {
                    b.Property<int>("IdMovimiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_movimiento");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("IdMovimiento"));

                    b.Property<string>("IdEconomico")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("id_economico");

                    b.Property<int?>("IdUbicacionLlegada")
                        .HasColumnType("integer")
                        .HasColumnName("id_ubicacion_llegada");

                    b.Property<int?>("IdUbicacionSalida")
                        .HasColumnType("integer")
                        .HasColumnName("id_ubicacion_salida");

                    b.Property<string>("UbicacionPersonalizada")
                        .HasColumnType("text")
                        .HasColumnName("ubicacion_personalizada");

                    b.HasKey("IdMovimiento")
                        .HasName("catalogo_movimientos_economicos_pkey");

                    b.HasIndex(new[] { "IdEconomico" }, "IX_catalogo_movimientos_economicos_id_economico");

                    b.HasIndex(new[] { "IdUbicacionLlegada" }, "IX_catalogo_movimientos_economicos_id_ubicacion_llegada");

                    b.HasIndex(new[] { "IdUbicacionSalida" }, "IX_catalogo_movimientos_economicos_id_ubicacion_salida");

                    b.ToTable("catalogo_movimientos_economicos", (string)null);
                });

            modelBuilder.Entity("Inventario.Data.Models.CatalogoOperadore", b =>
                {
                    b.Property<int>("IdOperador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_operador");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("IdOperador"));

                    b.Property<string>("NombreOperador")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre_operador");

                    b.HasKey("IdOperador")
                        .HasName("catalogo_operadores_pkey");

                    b.ToTable("catalogo_operadores", (string)null);
                });

            modelBuilder.Entity("Inventario.Data.Models.CatalogoPya", b =>
                {
                    b.Property<int>("IdPya")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_pya");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("IdPya"));

                    b.Property<int?>("IdRolPya")
                        .HasColumnType("integer")
                        .HasColumnName("id_rol_pya");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.HasKey("IdPya")
                        .HasName("catalogo_pya_pkey");

                    b.HasIndex(new[] { "IdRolPya" }, "IX_catalogo_pya_id_rol_pya");

                    b.ToTable("catalogo_pya", (string)null);
                });

            modelBuilder.Entity("Inventario.Data.Models.CatalogoResponsableMaquinarium", b =>
                {
                    b.Property<int>("IdResponsable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_responsable");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("IdResponsable"));

                    b.Property<string>("NombreResponsable")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre_responsable");

                    b.HasKey("IdResponsable")
                        .HasName("catalogo_responsable_maquinaria_pkey");

                    b.ToTable("catalogo_responsable_maquinaria", (string)null);
                });

            modelBuilder.Entity("Inventario.Data.Models.CatalogoRolPya", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_rol");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("IdRol"));

                    b.Property<string>("DescripcionRol")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descripcion_rol");

                    b.HasKey("IdRol")
                        .HasName("catalogo_rol_pya_pkey");

                    b.ToTable("catalogo_rol_pya", (string)null);
                });

            modelBuilder.Entity("Inventario.Data.Models.CatalogoTiposCombustible", b =>
                {
                    b.Property<int>("IdCombustible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_combustible");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("IdCombustible"));

                    b.Property<string>("DescripcionCombustible")
                        .HasColumnType("text")
                        .HasColumnName("descripcion_combustible");

                    b.HasKey("IdCombustible")
                        .HasName("catalogo_tipos_combustible_pkey");

                    b.ToTable("catalogo_tipos_combustible", (string)null);
                });

            modelBuilder.Entity("Inventario.Data.Models.CatalogoTiposEquipo", b =>
                {
                    b.Property<string>("IdTipoEquipo")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("id_tipo_equipo");

                    b.Property<string>("DescripcionTipoEquipo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descripcion_tipo_equipo");

                    b.HasKey("IdTipoEquipo")
                        .HasName("catalogo_tipos_equipos_pkey");

                    b.ToTable("catalogo_tipos_equipos", (string)null);
                });

            modelBuilder.Entity("Inventario.Data.Models.CatalogoTiposServicio", b =>
                {
                    b.Property<int>("IdTipoServicio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_tipo_servicio");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("IdTipoServicio"));

                    b.Property<string>("DescripcionServicio")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descripcion_servicio");

                    b.HasKey("IdTipoServicio")
                        .HasName("catalogo_tipos_servicios_pkey");

                    b.ToTable("catalogo_tipos_servicios", (string)null);
                });

            modelBuilder.Entity("Inventario.Data.Models.CatalogoTramo", b =>
                {
                    b.Property<int>("IdTramo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_tramo");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("IdTramo"));

                    b.Property<int>("IdUbicacion")
                        .HasColumnType("integer")
                        .HasColumnName("id_ubicacion");

                    b.Property<string>("NombreTramo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre_tramo");

                    b.HasKey("IdTramo")
                        .HasName("catalogo_tramos_pkey");

                    b.HasIndex(new[] { "IdUbicacion" }, "IX_catalogo_tramos_id_ubicacion");

                    b.ToTable("catalogo_tramos", (string)null);
                });

            modelBuilder.Entity("Inventario.Data.Models.CatalogoUbicacionesProyecto", b =>
                {
                    b.Property<int>("IdUbicacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_ubicacion");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("IdUbicacion"));

                    b.Property<string>("NombreProyecto")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre_proyecto");

                    b.Property<string>("Ubicacion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ubicacion");

                    b.HasKey("IdUbicacion")
                        .HasName("catalogo_ubicaciones_proyectos_pkey");

                    b.ToTable("catalogo_ubicaciones_proyectos", (string)null);
                });

            modelBuilder.Entity("Inventario.Data.Models.EconomicosArchivo", b =>
                {
                    b.Property<int>("IdEconomicoArchivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_economico_archivo");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdEconomicoArchivo"));

                    b.Property<int?>("IdArchivo")
                        .HasColumnType("integer")
                        .HasColumnName("id_archivo");

                    b.Property<string>("IdEconomico")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("id_economico");

                    b.HasKey("IdEconomicoArchivo")
                        .HasName("archivos_economicos_pkey");

                    b.HasIndex(new[] { "IdArchivo" }, "IX_economicos_archivos_id_archivo");

                    b.HasIndex(new[] { "IdEconomico" }, "IX_economicos_archivos_id_economico");

                    b.ToTable("economicos_archivos", (string)null);
                });

            modelBuilder.Entity("Inventario.Data.Models.HistorialLogs", b =>
                {
                    b.Property<int>("IdLog")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_log");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdLog"));

                    b.Property<string>("DescripcionLog")
                        .HasColumnType("text")
                        .HasColumnName("descripcion_log");

                    b.Property<DateTime?>("FechaLog")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_log");

                    b.Property<int?>("IdUsuario")
                        .HasColumnType("integer")
                        .HasColumnName("id_usuario");

                    b.Property<IPAddress>("IpAddress")
                        .HasColumnType("inet")
                        .HasColumnName("ip_address");

                    b.Property<string>("TipoLog")
                        .HasColumnType("text")
                        .HasColumnName("tipo_log");

                    b.HasKey("IdLog");

                    b.HasIndex("IdUsuario");

                    b.ToTable("historial_logs", (string)null);
                });

            modelBuilder.Entity("Inventario.Data.Models.ServiciosEconomico", b =>
                {
                    b.Property<int>("IdServicioEconomico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_servicio_economico");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("IdServicioEconomico"));

                    b.Property<DateOnly?>("FechaServicio")
                        .HasColumnType("date")
                        .HasColumnName("fecha_servicio");

                    b.Property<int?>("Horometro")
                        .HasColumnType("integer")
                        .HasColumnName("horometro");

                    b.Property<string>("IdEconomico")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("id_economico");

                    b.Property<int?>("IdTipoServicio")
                        .HasColumnType("integer")
                        .HasColumnName("id_tipo_servicio");

                    b.Property<int?>("Kilometraje")
                        .HasColumnType("integer")
                        .HasColumnName("kilometraje");

                    b.HasKey("IdServicioEconomico")
                        .HasName("servicios_economicos_pkey");

                    b.HasIndex(new[] { "IdEconomico" }, "IX_servicios_economicos_id_economico");

                    b.HasIndex(new[] { "IdTipoServicio" }, "IX_servicios_economicos_id_tipo_servicio");

                    b.ToTable("servicios_economicos", (string)null);
                });

            modelBuilder.Entity("Inventario.Data.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_usuario");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("IdUsuario"));

                    b.Property<int>("IdRol")
                        .HasColumnType("integer")
                        .HasColumnName("id_rol");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre_usuario");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.HasKey("IdUsuario")
                        .HasName("usuarios_pkey");

                    b.HasIndex("IdRol");

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("Inventario.Data.Models.UsuariosRole", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_rol");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("IdRol"));

                    b.Property<string>("DescripcionRol")
                        .HasColumnType("text")
                        .HasColumnName("descripcion_rol");

                    b.HasKey("IdRol")
                        .HasName("usurios_roles_pkey");

                    b.ToTable("usuarios_roles", (string)null);
                });

            modelBuilder.Entity("Inventario.Data.Models.UsuriosRole", b =>
                {
                    b.Property<int>("IdLog")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_log");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("IdLog"));

                    b.Property<int?>("IdUsuario")
                        .HasColumnType("integer")
                        .HasColumnName("id_usuario");

                    b.Property<string>("InformacionLog")
                        .HasColumnType("text")
                        .HasColumnName("informacion_log");

                    b.Property<string>("TipoLog")
                        .HasColumnType("text")
                        .HasColumnName("tipo_log");

                    b.HasKey("IdLog")
                        .HasName("usurios_roles_pkey1");

                    b.HasIndex("IdUsuario");

                    b.ToTable("usurios_roles", (string)null);
                });

            modelBuilder.Entity("Inventario.Data.Models.CatalogoEconomico", b =>
                {
                    b.HasOne("Inventario.Data.Models.CatalogoPya", "IdAdministradorNavigation")
                        .WithMany("CatalogoEconomicoIdAdministradorNavigations")
                        .HasForeignKey("IdAdministrador")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_administrador_economico");

                    b.HasOne("Inventario.Data.Models.CatalogoTiposCombustible", "IdCombustibleNavigation")
                        .WithMany("CatalogoEconomicos")
                        .HasForeignKey("IdCombustible")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_combustible_economico");

                    b.HasOne("Inventario.Data.Models.CatalogoEstatus", "IdEstatusNavigation")
                        .WithMany("CatalogoEconomicos")
                        .HasForeignKey("IdEstatus")
                        .HasConstraintName("fk_estatus_economico");

                    b.HasOne("Inventario.Data.Models.CatalogoGrupo", "IdGrupoNavigation")
                        .WithMany("CatalogoEconomicos")
                        .HasForeignKey("IdGrupo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_grupo_economico");

                    b.HasOne("Inventario.Data.Models.CatalogoMarca", "IdMarcaNavigation")
                        .WithMany("CatalogoEconomicoIdMarcaNavigations")
                        .HasForeignKey("IdMarca")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_marca_economico");

                    b.HasOne("Inventario.Data.Models.CatalogoOperadore", "IdOperadorNavigation")
                        .WithMany("CatalogoEconomicos")
                        .HasForeignKey("IdOperador")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_operador_economico");

                    b.HasOne("Inventario.Data.Models.CatalogoPya", "IdPropietarioNavigation")
                        .WithMany("CatalogoEconomicoIdPropietarioNavigations")
                        .HasForeignKey("IdPropietario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_propietario_economico");

                    b.HasOne("Inventario.Data.Models.CatalogoResponsableMaquinarium", "IdResponsableNavigation")
                        .WithMany("CatalogoEconomicos")
                        .HasForeignKey("IdResponsable")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_responsable_economico");

                    b.HasOne("Inventario.Data.Models.CatalogoTiposEquipo", "IdTipoEquipoNavigation")
                        .WithMany("CatalogoEconomicos")
                        .HasForeignKey("IdTipoEquipo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tipo_equipo_economico");

                    b.HasOne("Inventario.Data.Models.CatalogoUbicacionesProyecto", "IdUbicacionNavigation")
                        .WithMany("CatalogoEconomicos")
                        .HasForeignKey("IdUbicacion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ubicacion_economico");

                    b.HasOne("Inventario.Data.Models.CatalogoMarca", "MarcaMotorNavigation")
                        .WithMany("CatalogoEconomicoMarcaMotorNavigations")
                        .HasForeignKey("MarcaMotor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_marcamotor_economico");

                    b.Navigation("IdAdministradorNavigation");

                    b.Navigation("IdCombustibleNavigation");

                    b.Navigation("IdEstatusNavigation");

                    b.Navigation("IdGrupoNavigation");

                    b.Navigation("IdMarcaNavigation");

                    b.Navigation("IdOperadorNavigation");

                    b.Navigation("IdPropietarioNavigation");

                    b.Navigation("IdResponsableNavigation");

                    b.Navigation("IdTipoEquipoNavigation");

                    b.Navigation("IdUbicacionNavigation");

                    b.Navigation("MarcaMotorNavigation");
                });

            modelBuilder.Entity("Inventario.Data.Models.CatalogoFrente", b =>
                {
                    b.HasOne("Inventario.Data.Models.CatalogoTramo", "IdTramoNavigation")
                        .WithMany("CatalogoFrentes")
                        .HasForeignKey("IdTramo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ubicacion");

                    b.Navigation("IdTramoNavigation");
                });

            modelBuilder.Entity("Inventario.Data.Models.CatalogoMovimientosEconomico", b =>
                {
                    b.HasOne("Inventario.Data.Models.CatalogoEconomico", "IdEconomicoNavigation")
                        .WithMany("CatalogoMovimientosEconomicos")
                        .HasForeignKey("IdEconomico")
                        .HasConstraintName("fk_economico_ubicacion");

                    b.HasOne("Inventario.Data.Models.CatalogoUbicacionesProyecto", "IdUbicacionLlegadaNavigation")
                        .WithMany("CatalogoMovimientosEconomicoIdUbicacionLlegadaNavigations")
                        .HasForeignKey("IdUbicacionLlegada")
                        .HasConstraintName("fk_llegada_proyecto_ubicacion");

                    b.HasOne("Inventario.Data.Models.CatalogoUbicacionesProyecto", "IdUbicacionSalidaNavigation")
                        .WithMany("CatalogoMovimientosEconomicoIdUbicacionSalidaNavigations")
                        .HasForeignKey("IdUbicacionSalida")
                        .HasConstraintName("fk_salida_proyecto_ubicacion");

                    b.Navigation("IdEconomicoNavigation");

                    b.Navigation("IdUbicacionLlegadaNavigation");

                    b.Navigation("IdUbicacionSalidaNavigation");
                });

            modelBuilder.Entity("Inventario.Data.Models.CatalogoPya", b =>
                {
                    b.HasOne("Inventario.Data.Models.CatalogoRolPya", "IdRolPyaNavigation")
                        .WithMany("CatalogoPyas")
                        .HasForeignKey("IdRolPya")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_rol_pya");

                    b.Navigation("IdRolPyaNavigation");
                });

            modelBuilder.Entity("Inventario.Data.Models.CatalogoTramo", b =>
                {
                    b.HasOne("Inventario.Data.Models.CatalogoUbicacionesProyecto", "IdUbicacionNavigation")
                        .WithMany("CatalogoTramos")
                        .HasForeignKey("IdUbicacion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ubicacion");

                    b.Navigation("IdUbicacionNavigation");
                });

            modelBuilder.Entity("Inventario.Data.Models.EconomicosArchivo", b =>
                {
                    b.HasOne("Inventario.Data.Models.CatalogoArchivo", "IdArchivoNavigation")
                        .WithMany("EconomicosArchivos")
                        .HasForeignKey("IdArchivo")
                        .HasConstraintName("fk_archivo_economico");

                    b.HasOne("Inventario.Data.Models.CatalogoEconomico", "IdEconomicoNavigation")
                        .WithMany("EconomicosArchivos")
                        .HasForeignKey("IdEconomico")
                        .HasConstraintName("fk_economico_archivo");

                    b.Navigation("IdArchivoNavigation");

                    b.Navigation("IdEconomicoNavigation");
                });

            modelBuilder.Entity("Inventario.Data.Models.HistorialLogs", b =>
                {
                    b.HasOne("Inventario.Data.Models.Usuario", "IdUsuarioNavigation")
                        .WithMany("HistorialLogs")
                        .HasForeignKey("IdUsuario")
                        .HasConstraintName("fk_usuario");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("Inventario.Data.Models.ServiciosEconomico", b =>
                {
                    b.HasOne("Inventario.Data.Models.CatalogoEconomico", "IdEconomicoNavigation")
                        .WithMany("ServiciosEconomicos")
                        .HasForeignKey("IdEconomico")
                        .HasConstraintName("fk_economico_servicio");

                    b.HasOne("Inventario.Data.Models.CatalogoTiposServicio", "IdTipoServicioNavigation")
                        .WithMany("ServiciosEconomicos")
                        .HasForeignKey("IdTipoServicio")
                        .HasConstraintName("fk_servicio_economico");

                    b.Navigation("IdEconomicoNavigation");

                    b.Navigation("IdTipoServicioNavigation");
                });

            modelBuilder.Entity("Inventario.Data.Models.Usuario", b =>
                {
                    b.HasOne("Inventario.Data.Models.UsuariosRole", "IdRolNavigation")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_usuario_rol");

                    b.Navigation("IdRolNavigation");
                });

            modelBuilder.Entity("Inventario.Data.Models.UsuriosRole", b =>
                {
                    b.HasOne("Inventario.Data.Models.Usuario", "IdUsuarioNavigation")
                        .WithMany("UsuriosRoles")
                        .HasForeignKey("IdUsuario")
                        .HasConstraintName("fk_log_usuario");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("Inventario.Data.Models.CatalogoArchivo", b =>
                {
                    b.Navigation("EconomicosArchivos");
                });

            modelBuilder.Entity("Inventario.Data.Models.CatalogoEconomico", b =>
                {
                    b.Navigation("CatalogoMovimientosEconomicos");

                    b.Navigation("EconomicosArchivos");

                    b.Navigation("ServiciosEconomicos");
                });

            modelBuilder.Entity("Inventario.Data.Models.CatalogoEstatus", b =>
                {
                    b.Navigation("CatalogoEconomicos");
                });

            modelBuilder.Entity("Inventario.Data.Models.CatalogoGrupo", b =>
                {
                    b.Navigation("CatalogoEconomicos");
                });

            modelBuilder.Entity("Inventario.Data.Models.CatalogoMarca", b =>
                {
                    b.Navigation("CatalogoEconomicoIdMarcaNavigations");

                    b.Navigation("CatalogoEconomicoMarcaMotorNavigations");
                });

            modelBuilder.Entity("Inventario.Data.Models.CatalogoOperadore", b =>
                {
                    b.Navigation("CatalogoEconomicos");
                });

            modelBuilder.Entity("Inventario.Data.Models.CatalogoPya", b =>
                {
                    b.Navigation("CatalogoEconomicoIdAdministradorNavigations");

                    b.Navigation("CatalogoEconomicoIdPropietarioNavigations");
                });

            modelBuilder.Entity("Inventario.Data.Models.CatalogoResponsableMaquinarium", b =>
                {
                    b.Navigation("CatalogoEconomicos");
                });

            modelBuilder.Entity("Inventario.Data.Models.CatalogoRolPya", b =>
                {
                    b.Navigation("CatalogoPyas");
                });

            modelBuilder.Entity("Inventario.Data.Models.CatalogoTiposCombustible", b =>
                {
                    b.Navigation("CatalogoEconomicos");
                });

            modelBuilder.Entity("Inventario.Data.Models.CatalogoTiposEquipo", b =>
                {
                    b.Navigation("CatalogoEconomicos");
                });

            modelBuilder.Entity("Inventario.Data.Models.CatalogoTiposServicio", b =>
                {
                    b.Navigation("ServiciosEconomicos");
                });

            modelBuilder.Entity("Inventario.Data.Models.CatalogoTramo", b =>
                {
                    b.Navigation("CatalogoFrentes");
                });

            modelBuilder.Entity("Inventario.Data.Models.CatalogoUbicacionesProyecto", b =>
                {
                    b.Navigation("CatalogoEconomicos");

                    b.Navigation("CatalogoMovimientosEconomicoIdUbicacionLlegadaNavigations");

                    b.Navigation("CatalogoMovimientosEconomicoIdUbicacionSalidaNavigations");

                    b.Navigation("CatalogoTramos");
                });

            modelBuilder.Entity("Inventario.Data.Models.Usuario", b =>
                {
                    b.Navigation("HistorialLogs");

                    b.Navigation("UsuriosRoles");
                });

            modelBuilder.Entity("Inventario.Data.Models.UsuariosRole", b =>
                {
                    b.Navigation("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
