// <auto-generated />
using System;
using Inventario.Data.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Inventario.Data.Migrations
{
    [DbContext(typeof(InventarioContext))]
    partial class InventarioContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_0900_ai_ci")
                .HasAnnotation("ProductVersion", "9.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Inventario.Data.Models.CatalogoArchivo", b =>
                {
                    b.Property<int>("IdArchivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_archivo");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdArchivo"));

                    b.Property<string>("Archivo")
                        .HasColumnType("text")
                        .HasColumnName("archivo");

                    b.Property<DateTime?>("FechaSubida")
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_subida");

                    b.Property<string>("NombreArchivo")
                        .HasColumnType("text")
                        .HasColumnName("nombre_archivo");

                    b.HasKey("IdArchivo")
                        .HasName("PRIMARY");

                    b.ToTable("catalogo_archivos", (string)null);

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_general_ci");
                });

            modelBuilder.Entity("Inventario.Data.Models.CatalogoEconomico", b =>
                {
                    b.Property<string>("IdEconomico")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("id_economico");

                    b.Property<int?>("Consecutivo")
                        .HasColumnType("int")
                        .HasColumnName("consecutivo");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<string>("Dimensiones")
                        .HasColumnType("text")
                        .HasColumnName("dimensiones");

                    b.Property<bool?>("EstatusSeguro")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("estatus_seguro");

                    b.Property<string>("FamiliaMotor")
                        .HasColumnType("text")
                        .HasColumnName("familia_motor");

                    b.Property<string>("GradoPropiedad")
                        .HasColumnType("text")
                        .HasColumnName("grado_propiedad");

                    b.Property<decimal?>("Horometro")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("horometro");

                    b.Property<int?>("IdAdministrador")
                        .HasColumnType("int")
                        .HasColumnName("id_administrador");

                    b.Property<int?>("IdCombustible")
                        .HasColumnType("int")
                        .HasColumnName("id_combustible");

                    b.Property<int?>("IdEstatus")
                        .HasColumnType("int")
                        .HasColumnName("id_estatus");

                    b.Property<string>("IdGrupo")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("id_grupo");

                    b.Property<int?>("IdMarca")
                        .HasColumnType("int")
                        .HasColumnName("id_marca");

                    b.Property<int?>("IdOperador")
                        .HasColumnType("int")
                        .HasColumnName("id_operador");

                    b.Property<int?>("IdPropietario")
                        .HasColumnType("int")
                        .HasColumnName("id_propietario");

                    b.Property<int?>("IdResponsable")
                        .HasColumnType("int")
                        .HasColumnName("id_responsable");

                    b.Property<string>("IdTipoEquipo")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("id_tipo_equipo");

                    b.Property<int?>("IdUbicacion")
                        .HasColumnType("int")
                        .HasColumnName("id_ubicacion");

                    b.Property<int?>("MarcaMotor")
                        .HasColumnType("int")
                        .HasColumnName("marca_motor");

                    b.Property<string>("Modelo")
                        .HasColumnType("text")
                        .HasColumnName("modelo");

                    b.Property<string>("ModeloMotor")
                        .HasColumnType("text")
                        .HasColumnName("modelo_motor");

                    b.Property<string>("Motor")
                        .HasColumnType("text")
                        .HasColumnName("motor");

                    b.Property<string>("ObservacionesAsignaciones")
                        .HasColumnType("text")
                        .HasColumnName("observaciones_asignaciones");

                    b.Property<int?>("PeriodoFabricacion")
                        .HasColumnType("int")
                        .HasColumnName("periodo_fabricacion");

                    b.Property<string>("Placas")
                        .HasColumnType("text")
                        .HasColumnName("placas");

                    b.Property<string>("Serie")
                        .HasColumnType("text")
                        .HasColumnName("serie");

                    b.Property<string>("SerieMotor")
                        .HasColumnType("text")
                        .HasColumnName("serie_motor");

                    b.Property<string>("Thk")
                        .HasColumnType("text")
                        .HasColumnName("thk");

                    b.Property<string>("TipoSeguro")
                        .HasColumnType("text")
                        .HasColumnName("tipo_seguro");

                    b.Property<decimal?>("ValorAdquisicion")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("valor_adquisicion");

                    b.Property<bool?>("Verificado")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("verificado");

                    b.HasKey("IdEconomico")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdAdministrador" }, "fk_administrador_economico");

                    b.HasIndex(new[] { "IdCombustible" }, "fk_eco_combustible");

                    b.HasIndex(new[] { "IdEstatus" }, "fk_eco_estatus");

                    b.HasIndex(new[] { "IdGrupo" }, "fk_eco_grupo");

                    b.HasIndex(new[] { "IdMarca" }, "fk_eco_marca");

                    b.HasIndex(new[] { "MarcaMotor" }, "fk_eco_marca_motor");

                    b.HasIndex(new[] { "IdTipoEquipo" }, "fk_eco_tipo_equipo");

                    b.HasIndex(new[] { "IdUbicacion" }, "fk_eco_ubicacion");

                    b.HasIndex(new[] { "IdOperador" }, "fk_operador_economico");

                    b.HasIndex(new[] { "IdPropietario" }, "fk_propietario_economico");

                    b.HasIndex(new[] { "IdResponsable" }, "fk_responsabgle_economico");

                    b.ToTable("catalogo_economicos", (string)null);

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_general_ci");
                });

            modelBuilder.Entity("Inventario.Data.Models.CatalogoEstatus", b =>
                {
                    b.Property<int>("IdEstatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_estatus");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdEstatus"));

                    b.Property<string>("DescripcionEstatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descripcion_estatus");

                    b.HasKey("IdEstatus")
                        .HasName("PRIMARY");

                    b.ToTable("catalogo_estatus", (string)null);

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_general_ci");
                });

            modelBuilder.Entity("Inventario.Data.Models.CatalogoFrente", b =>
                {
                    b.Property<int>("IdFrente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_frente");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdFrente"));

                    b.Property<int?>("IdTramo")
                        .HasColumnType("int")
                        .HasColumnName("id_tramo");

                    b.Property<string>("NombreFrente")
                        .HasColumnType("text")
                        .HasColumnName("nombre_frente");

                    b.HasKey("IdFrente")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdTramo" }, "fk_frente_tramo");

                    b.ToTable("catalogo_frentes", (string)null);

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_general_ci");
                });

            modelBuilder.Entity("Inventario.Data.Models.CatalogoGrupo", b =>
                {
                    b.Property<string>("IdGrupo")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("id_grupo");

                    b.Property<string>("DescripcionGrupo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descripcion_grupo");

                    b.HasKey("IdGrupo")
                        .HasName("PRIMARY");

                    b.ToTable("catalogo_grupos", (string)null);

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_general_ci");
                });

            modelBuilder.Entity("Inventario.Data.Models.CatalogoMarca", b =>
                {
                    b.Property<int>("IdMarca")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_marca");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdMarca"));

                    b.Property<string>("NombreMarca")
                        .HasColumnType("text")
                        .HasColumnName("nombre_marca");

                    b.HasKey("IdMarca")
                        .HasName("PRIMARY");

                    b.ToTable("catalogo_marcas", (string)null);

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_general_ci");
                });

            modelBuilder.Entity("Inventario.Data.Models.CatalogoMovimientosEconomico", b =>
                {
                    b.Property<int>("IdMovimiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_movimiento");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdMovimiento"));

                    b.Property<string>("Archivo")
                        .HasColumnType("text")
                        .HasColumnName("archivo");

                    b.Property<string>("Archivo2")
                        .HasColumnType("text")
                        .HasColumnName("archivo_2");

                    b.Property<DateTime?>("FechaMovimiento")
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_movimiento");

                    b.Property<string>("IdEconomico")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("id_economico")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<int?>("IdUbicacionLlegada")
                        .HasColumnType("int")
                        .HasColumnName("id_ubicacion_llegada");

                    b.Property<int?>("IdUbicacionSalida")
                        .HasColumnType("int")
                        .HasColumnName("id_ubicacion_salida");

                    b.Property<int?>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    b.Property<string>("NombreArchivo")
                        .HasColumnType("text")
                        .HasColumnName("nombre_archivo");

                    b.Property<string>("NombreArchivo2")
                        .HasColumnType("text")
                        .HasColumnName("nombre_archivo_2");

                    b.Property<string>("UbicacionPersonalizada")
                        .HasColumnType("text")
                        .HasColumnName("ubicacion_personalizada");

                    b.HasKey("IdMovimiento")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdEconomico" }, "fk_economico_movimiento");

                    b.HasIndex(new[] { "IdUbicacionLlegada" }, "fk_ubicacion_llegada_movimiento");

                    b.HasIndex(new[] { "IdUbicacionSalida" }, "fk_ubicacion_salida_movimiento");

                    b.HasIndex(new[] { "IdUsuario" }, "fk_usuario_movimiento");

                    b.ToTable("catalogo_movimientos_economicos", (string)null);
                });

            modelBuilder.Entity("Inventario.Data.Models.CatalogoProveedore", b =>
                {
                    b.Property<int>("IdProveedor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_proveedor");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdProveedor"));

                    b.Property<string>("CorreoElectronico")
                        .HasColumnType("text")
                        .HasColumnName("correo_electronico");

                    b.Property<string>("NombreProveedor")
                        .HasColumnType("text")
                        .HasColumnName("nombre_proveedor");

                    b.Property<string>("NumeroContacto")
                        .HasColumnType("text")
                        .HasColumnName("numero_contacto");

                    b.HasKey("IdProveedor")
                        .HasName("PRIMARY");

                    b.ToTable("catalogo_proveedores", (string)null);

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_general_ci");
                });

            modelBuilder.Entity("Inventario.Data.Models.CatalogoPya", b =>
                {
                    b.Property<int>("IdPya")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_pya");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdPya"));

                    b.Property<int?>("IdRolPya")
                        .HasColumnType("int")
                        .HasColumnName("id_rol_pya");

                    b.Property<string>("Nombre")
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.HasKey("IdPya")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdRolPya" }, "fk_rol_pya");

                    b.ToTable("catalogo_pya", (string)null);

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_general_ci");
                });

            modelBuilder.Entity("Inventario.Data.Models.CatalogoRolPya", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_rol");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdRol"));

                    b.Property<string>("DescripcionRol")
                        .HasColumnType("text")
                        .HasColumnName("descripcion_rol");

                    b.HasKey("IdRol")
                        .HasName("PRIMARY");

                    b.ToTable("catalogo_rol_pya", (string)null);

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_general_ci");
                });

            modelBuilder.Entity("Inventario.Data.Models.CatalogoTiposCombustible", b =>
                {
                    b.Property<int>("IdCombustible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_combustible");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdCombustible"));

                    b.Property<string>("DescripcionCombustible")
                        .HasColumnType("text")
                        .HasColumnName("descripcion_combustible");

                    b.HasKey("IdCombustible")
                        .HasName("PRIMARY");

                    b.ToTable("catalogo_tipos_combustible", (string)null);

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_general_ci");
                });

            modelBuilder.Entity("Inventario.Data.Models.CatalogoTiposEquipo", b =>
                {
                    b.Property<string>("IdTipoEquipo")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("id_tipo_equipo");

                    b.Property<string>("DescripcionTipoEquipo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descripcion_tipo_equipo");

                    b.HasKey("IdTipoEquipo")
                        .HasName("PRIMARY");

                    b.ToTable("catalogo_tipos_equipos", (string)null);

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_general_ci");
                });

            modelBuilder.Entity("Inventario.Data.Models.CatalogoTramo", b =>
                {
                    b.Property<int>("IdTramo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_tramo");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdTramo"));

                    b.Property<int?>("IdUbicacion")
                        .HasColumnType("int")
                        .HasColumnName("id_ubicacion");

                    b.Property<string>("NombreTramo")
                        .HasColumnType("text")
                        .HasColumnName("nombre_tramo");

                    b.HasKey("IdTramo")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdUbicacion" }, "fk_ubicacion_tramo");

                    b.ToTable("catalogo_tramos", (string)null);

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_general_ci");
                });

            modelBuilder.Entity("Inventario.Data.Models.CatalogoUbicacionesProyecto", b =>
                {
                    b.Property<int>("IdUbicacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_ubicacion");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdUbicacion"));

                    b.Property<string>("NombreProyecto")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre_proyecto");

                    b.Property<string>("Siglas")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("siglas");

                    b.Property<string>("Ubicacion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ubicacion");

                    b.HasKey("IdUbicacion")
                        .HasName("PRIMARY");

                    b.ToTable("catalogo_ubicaciones_proyectos", (string)null);

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_general_ci");
                });

            modelBuilder.Entity("Inventario.Data.Models.EconomicosArchivo", b =>
                {
                    b.Property<int>("IdEconomicoArchivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_economico_archivo");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdEconomicoArchivo"));

                    b.Property<int?>("IdArchivo")
                        .HasColumnType("int")
                        .HasColumnName("id_archivo");

                    b.Property<string>("IdEconomico")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("id_economico");

                    b.HasKey("IdEconomicoArchivo")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdArchivo" }, "fk_archivo_archivoeconomico");

                    b.HasIndex(new[] { "IdEconomico" }, "fk_economico_archivoeconomico");

                    b.ToTable("economicos_archivos", (string)null);

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_general_ci");
                });

            modelBuilder.Entity("Inventario.Data.Models.EfmigrationsHistory", b =>
                {
                    b.Property<string>("MigrationId")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("ProductVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.HasKey("MigrationId")
                        .HasName("PRIMARY");

                    b.ToTable("__EFMigrationsHistory", (string)null);
                });

            modelBuilder.Entity("Inventario.Data.Models.Empleado", b =>
                {
                    b.Property<int>("NoEmpleado")
                        .HasColumnType("int")
                        .HasColumnName("no_empleado");

                    b.Property<DateOnly?>("Ds3")
                        .HasColumnType("date")
                        .HasColumnName("ds3");

                    b.Property<int?>("IdRolEmpleado")
                        .HasColumnType("int")
                        .HasColumnName("id_rol_empleado");

                    b.Property<string>("NombreEmpleado")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("nombre_empleado");

                    b.HasKey("NoEmpleado")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdRolEmpleado" }, "fk_rolempleado_empleado");

                    b.ToTable("empleados", (string)null);

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_general_ci");
                });

            modelBuilder.Entity("Inventario.Data.Models.HistorialLog", b =>
                {
                    b.Property<int>("IdLog")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_log");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdLog"));

                    b.Property<string>("DescripcionLog")
                        .HasColumnType("text")
                        .HasColumnName("descripcion_log");

                    b.Property<DateTime?>("FechaLog")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_log")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("ip_address");

                    b.Property<string>("TipoLog")
                        .HasColumnType("text")
                        .HasColumnName("tipo_log");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text")
                        .HasColumnName("user_agent");

                    b.HasKey("IdLog")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdUsuario" }, "fk_log_usuario");

                    b.ToTable("historial_logs", (string)null);

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_general_ci");
                });

            modelBuilder.Entity("Inventario.Data.Models.HistorialServicio", b =>
                {
                    b.Property<int>("IdServicio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_servicio");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdServicio"));

                    b.Property<string>("Anotaciones")
                        .HasColumnType("text")
                        .HasColumnName("anotaciones");

                    b.Property<DateOnly?>("FechaMantenimiento")
                        .HasColumnType("date")
                        .HasColumnName("fecha_mantenimiento");

                    b.Property<string>("NoEconomico")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("no_economico")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<string>("TipoMantenimiento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("tipo_mantenimiento");

                    b.HasKey("IdServicio")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "NoEconomico" }, "fk_economico_servicio");

                    b.ToTable("historial_servicio", (string)null);
                });

            modelBuilder.Entity("Inventario.Data.Models.Requisicione", b =>
                {
                    b.Property<string>("IdRequisicion")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("id_requisicion");

                    b.Property<int?>("Consecutivo")
                        .HasColumnType("int")
                        .HasColumnName("consecutivo");

                    b.Property<DateOnly?>("FechaRequisicion")
                        .HasColumnType("date")
                        .HasColumnName("fecha_requisicion");

                    b.Property<int?>("IdUbicacion")
                        .HasColumnType("int")
                        .HasColumnName("id_ubicacion");

                    b.Property<string>("RazonSocial")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("razon_social");

                    b.Property<string>("TipoRequisicion")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("tipo_requisicion");

                    b.HasKey("IdRequisicion")
                        .HasName("PRIMARY");

                    b.ToTable("requisiciones", (string)null);

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_general_ci");
                });

            modelBuilder.Entity("Inventario.Data.Models.RolEmpleado", b =>
                {
                    b.Property<int>("IdRolEmpleado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_rol_empleado");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdRolEmpleado"));

                    b.Property<string>("DescripcionRol")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("descripcion_rol");

                    b.HasKey("IdRolEmpleado")
                        .HasName("PRIMARY");

                    b.ToTable("rol_empleado", (string)null);

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_general_ci");
                });

            modelBuilder.Entity("Inventario.Data.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<int?>("IdRol")
                        .HasColumnType("int")
                        .HasColumnName("id_rol");

                    b.Property<string>("NombreUsuario")
                        .HasColumnType("text")
                        .HasColumnName("nombre_usuario");

                    b.Property<string>("Password")
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.HasKey("IdUsuario")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdRol" }, "fk_usuarios_roles");

                    b.ToTable("usuarios", (string)null);

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_general_ci");
                });

            modelBuilder.Entity("Inventario.Data.Models.UsuariosRole", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_rol");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdRol"));

                    b.Property<string>("DescripcionRol")
                        .HasColumnType("text")
                        .HasColumnName("descripcion_rol");

                    b.HasKey("IdRol")
                        .HasName("PRIMARY");

                    b.ToTable("usuarios_roles", (string)null);

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_general_ci");
                });

            modelBuilder.Entity("Inventario.Data.Models.CatalogoEconomico", b =>
                {
                    b.HasOne("Inventario.Data.Models.CatalogoPya", "IdAdministradorNavigation")
                        .WithMany("CatalogoEconomicoIdAdministradorNavigations")
                        .HasForeignKey("IdAdministrador")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_administrador_economico");

                    b.HasOne("Inventario.Data.Models.CatalogoTiposCombustible", "IdCombustibleNavigation")
                        .WithMany("CatalogoEconomicos")
                        .HasForeignKey("IdCombustible")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_eco_combustible");

                    b.HasOne("Inventario.Data.Models.CatalogoEstatus", "IdEstatusNavigation")
                        .WithMany("CatalogoEconomicos")
                        .HasForeignKey("IdEstatus")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_eco_estatus");

                    b.HasOne("Inventario.Data.Models.CatalogoGrupo", "IdGrupoNavigation")
                        .WithMany("CatalogoEconomicos")
                        .HasForeignKey("IdGrupo")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_eco_grupo");

                    b.HasOne("Inventario.Data.Models.CatalogoMarca", "IdMarcaNavigation")
                        .WithMany("CatalogoEconomicoIdMarcaNavigations")
                        .HasForeignKey("IdMarca")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_eco_marca");

                    b.HasOne("Inventario.Data.Models.Empleado", "IdOperadorNavigation")
                        .WithMany("CatalogoEconomicoIdOperadorNavigations")
                        .HasForeignKey("IdOperador")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_operador_economico");

                    b.HasOne("Inventario.Data.Models.CatalogoPya", "IdPropietarioNavigation")
                        .WithMany("CatalogoEconomicoIdPropietarioNavigations")
                        .HasForeignKey("IdPropietario")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_propietario_economico");

                    b.HasOne("Inventario.Data.Models.Empleado", "IdResponsableNavigation")
                        .WithMany("CatalogoEconomicoIdResponsableNavigations")
                        .HasForeignKey("IdResponsable")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_responsabgle_economico");

                    b.HasOne("Inventario.Data.Models.CatalogoTiposEquipo", "IdTipoEquipoNavigation")
                        .WithMany("CatalogoEconomicos")
                        .HasForeignKey("IdTipoEquipo")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_eco_tipo_equipo");

                    b.HasOne("Inventario.Data.Models.CatalogoUbicacionesProyecto", "IdUbicacionNavigation")
                        .WithMany("CatalogoEconomicos")
                        .HasForeignKey("IdUbicacion")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_eco_ubicacion");

                    b.HasOne("Inventario.Data.Models.CatalogoMarca", "MarcaMotorNavigation")
                        .WithMany("CatalogoEconomicoMarcaMotorNavigations")
                        .HasForeignKey("MarcaMotor")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_eco_marca_motor");

                    b.Navigation("IdAdministradorNavigation");

                    b.Navigation("IdCombustibleNavigation");

                    b.Navigation("IdEstatusNavigation");

                    b.Navigation("IdGrupoNavigation");

                    b.Navigation("IdMarcaNavigation");

                    b.Navigation("IdOperadorNavigation");

                    b.Navigation("IdPropietarioNavigation");

                    b.Navigation("IdResponsableNavigation");

                    b.Navigation("IdTipoEquipoNavigation");

                    b.Navigation("IdUbicacionNavigation");

                    b.Navigation("MarcaMotorNavigation");
                });

            modelBuilder.Entity("Inventario.Data.Models.CatalogoFrente", b =>
                {
                    b.HasOne("Inventario.Data.Models.CatalogoTramo", "IdTramoNavigation")
                        .WithMany("CatalogoFrentes")
                        .HasForeignKey("IdTramo")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_frente_tramo");

                    b.Navigation("IdTramoNavigation");
                });

            modelBuilder.Entity("Inventario.Data.Models.CatalogoMovimientosEconomico", b =>
                {
                    b.HasOne("Inventario.Data.Models.CatalogoEconomico", "IdEconomicoNavigation")
                        .WithMany("CatalogoMovimientosEconomicos")
                        .HasForeignKey("IdEconomico")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_economico_movimiento");

                    b.HasOne("Inventario.Data.Models.CatalogoUbicacionesProyecto", "IdUbicacionLlegadaNavigation")
                        .WithMany("CatalogoMovimientosEconomicoIdUbicacionLlegadaNavigations")
                        .HasForeignKey("IdUbicacionLlegada")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_ubicacion_llegada_movimiento");

                    b.HasOne("Inventario.Data.Models.CatalogoUbicacionesProyecto", "IdUbicacionSalidaNavigation")
                        .WithMany("CatalogoMovimientosEconomicoIdUbicacionSalidaNavigations")
                        .HasForeignKey("IdUbicacionSalida")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_ubicacion_salida_movimiento");

                    b.HasOne("Inventario.Data.Models.Usuario", "IdUsuarioNavigation")
                        .WithMany("CatalogoMovimientosEconomicos")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_usuario_movimiento");

                    b.Navigation("IdEconomicoNavigation");

                    b.Navigation("IdUbicacionLlegadaNavigation");

                    b.Navigation("IdUbicacionSalidaNavigation");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("Inventario.Data.Models.CatalogoPya", b =>
                {
                    b.HasOne("Inventario.Data.Models.CatalogoRolPya", "IdRolPyaNavigation")
                        .WithMany("CatalogoPyas")
                        .HasForeignKey("IdRolPya")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_rol_pya");

                    b.Navigation("IdRolPyaNavigation");
                });

            modelBuilder.Entity("Inventario.Data.Models.CatalogoTramo", b =>
                {
                    b.HasOne("Inventario.Data.Models.CatalogoUbicacionesProyecto", "IdUbicacionNavigation")
                        .WithMany("CatalogoTramos")
                        .HasForeignKey("IdUbicacion")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_ubicacion_tramo");

                    b.Navigation("IdUbicacionNavigation");
                });

            modelBuilder.Entity("Inventario.Data.Models.EconomicosArchivo", b =>
                {
                    b.HasOne("Inventario.Data.Models.CatalogoArchivo", "IdArchivoNavigation")
                        .WithMany("EconomicosArchivos")
                        .HasForeignKey("IdArchivo")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_archivo_archivoeconomico");

                    b.HasOne("Inventario.Data.Models.CatalogoEconomico", "IdEconomicoNavigation")
                        .WithMany("EconomicosArchivos")
                        .HasForeignKey("IdEconomico")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_economico_archivoeconomico");

                    b.Navigation("IdArchivoNavigation");

                    b.Navigation("IdEconomicoNavigation");
                });

            modelBuilder.Entity("Inventario.Data.Models.Empleado", b =>
                {
                    b.HasOne("Inventario.Data.Models.RolEmpleado", "IdRolEmpleadoNavigation")
                        .WithMany("Empleados")
                        .HasForeignKey("IdRolEmpleado")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_rolempleado_empleado");

                    b.Navigation("IdRolEmpleadoNavigation");
                });

            modelBuilder.Entity("Inventario.Data.Models.HistorialLog", b =>
                {
                    b.HasOne("Inventario.Data.Models.Usuario", "IdUsuarioNavigation")
                        .WithMany("HistorialLogs")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_log_usuario");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("Inventario.Data.Models.HistorialServicio", b =>
                {
                    b.HasOne("Inventario.Data.Models.CatalogoEconomico", "NoEconomicoNavigation")
                        .WithMany("HistorialServicios")
                        .HasForeignKey("NoEconomico")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_economico_servicio");

                    b.Navigation("NoEconomicoNavigation");
                });

            modelBuilder.Entity("Inventario.Data.Models.Usuario", b =>
                {
                    b.HasOne("Inventario.Data.Models.UsuariosRole", "IdRolNavigation")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_usuarios_roles");

                    b.Navigation("IdRolNavigation");
                });

            modelBuilder.Entity("Inventario.Data.Models.CatalogoArchivo", b =>
                {
                    b.Navigation("EconomicosArchivos");
                });

            modelBuilder.Entity("Inventario.Data.Models.CatalogoEconomico", b =>
                {
                    b.Navigation("CatalogoMovimientosEconomicos");

                    b.Navigation("EconomicosArchivos");

                    b.Navigation("HistorialServicios");
                });

            modelBuilder.Entity("Inventario.Data.Models.CatalogoEstatus", b =>
                {
                    b.Navigation("CatalogoEconomicos");
                });

            modelBuilder.Entity("Inventario.Data.Models.CatalogoGrupo", b =>
                {
                    b.Navigation("CatalogoEconomicos");
                });

            modelBuilder.Entity("Inventario.Data.Models.CatalogoMarca", b =>
                {
                    b.Navigation("CatalogoEconomicoIdMarcaNavigations");

                    b.Navigation("CatalogoEconomicoMarcaMotorNavigations");
                });

            modelBuilder.Entity("Inventario.Data.Models.CatalogoPya", b =>
                {
                    b.Navigation("CatalogoEconomicoIdAdministradorNavigations");

                    b.Navigation("CatalogoEconomicoIdPropietarioNavigations");
                });

            modelBuilder.Entity("Inventario.Data.Models.CatalogoRolPya", b =>
                {
                    b.Navigation("CatalogoPyas");
                });

            modelBuilder.Entity("Inventario.Data.Models.CatalogoTiposCombustible", b =>
                {
                    b.Navigation("CatalogoEconomicos");
                });

            modelBuilder.Entity("Inventario.Data.Models.CatalogoTiposEquipo", b =>
                {
                    b.Navigation("CatalogoEconomicos");
                });

            modelBuilder.Entity("Inventario.Data.Models.CatalogoTramo", b =>
                {
                    b.Navigation("CatalogoFrentes");
                });

            modelBuilder.Entity("Inventario.Data.Models.CatalogoUbicacionesProyecto", b =>
                {
                    b.Navigation("CatalogoEconomicos");

                    b.Navigation("CatalogoMovimientosEconomicoIdUbicacionLlegadaNavigations");

                    b.Navigation("CatalogoMovimientosEconomicoIdUbicacionSalidaNavigations");

                    b.Navigation("CatalogoTramos");
                });

            modelBuilder.Entity("Inventario.Data.Models.Empleado", b =>
                {
                    b.Navigation("CatalogoEconomicoIdOperadorNavigations");

                    b.Navigation("CatalogoEconomicoIdResponsableNavigations");
                });

            modelBuilder.Entity("Inventario.Data.Models.RolEmpleado", b =>
                {
                    b.Navigation("Empleados");
                });

            modelBuilder.Entity("Inventario.Data.Models.Usuario", b =>
                {
                    b.Navigation("CatalogoMovimientosEconomicos");

                    b.Navigation("HistorialLogs");
                });

            modelBuilder.Entity("Inventario.Data.Models.UsuariosRole", b =>
                {
                    b.Navigation("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
