name: Compilar y Publicar Actualizacion

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    # 1. Obtiene el código fuente
    - name: Checkout del código
      uses: actions/checkout@v4

    # 2. Configura el entorno de .NET
    - name: Configurar .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'

    # 3. Restaura las dependencias del proyecto
    - name: Restaurar NuGet
      run: dotnet restore

    # 4. Compila y publica el ejecutable WPF tomando la versión directo del csproj
    - name: Compilar WPF
      run: dotnet publish GalloMeda.InventarioMaqunaria/Inventario.Desktop.csproj --configuration Release -o ./publish /p:PublishSingleFile=true /p:SelfContained=false

    # 5. Comprime la compilación directamente (sin subcarpetas conflictivas)
    - name: Comprimir ejecutable
      run: Compress-Archive -Path ./publish/* -DestinationPath ./InventarioSetup.zip -Force

    # 6. Crea la Release en GitHub usando un tag automático basado en el contador
    - name: Publicar Release en GitHub
      uses: softprops/action-gh-release@v2
      with:
        files: ./InventarioSetup.zip
        tag_name: "v1.0.${{ github.run_number }}"
        name: "Actualización v1.0.${{ github.run_number }}"
        body: "Nueva actualización automática del sistema."
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}